permissions:
  contents: read
  actions: write

jobs:
  list-and-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: List all forks
        id: list_forks
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // same listing logic
            core.setOutput('forks', JSON.stringify(forks))

      - name: Dispatch sync event to each fork
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.DISPATCH_TOKEN }}
          script: |
            const forks = JSON.parse(process.env.FORKS);
            for (const repo of forks) {
              await github.rest.repos.createDispatchEvent({
                owner: repo.split('/')[0],
                repo: repo.split('/')[1],
                event_type: 'upstream-sync',
                client_payload: { upstream: 'cncf/foundation' }
              });
            }
        env:
          FORKS: ${{ steps.list_forks.outputs.forks }}
