name: 🔄 Sync all forks

on:
  schedule:
    - cron: '0 5 * * *'       # daily at 05:00 UTC
  workflow_dispatch:         # manual trigger

jobs:
  list-and-dispatch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      repository_dispatch: write

    strategy:
      matrix:
        repo: ${{ fromJson(steps.list_forks.outputs.repositories) }}

    steps:
      - name: List all forks in the org
        id: list_forks
        uses: peter-evans/list-repositories@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          org: le-fork
          type: forks

      - name: Dispatch sync event to each fork
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: upstream-sync
          client-payload: '{"upstream":"cncf/foundation"}'
          repository: ${{ matrix.repo }}
