name: 🔄 Sync all forks

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  list-forks:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.list.outputs.repositories }}
    steps:
      - name: List all forks
        id: list
        uses: peter-evans/list-repositories@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          org: le-fork
          type: forks

  dispatch-sync:
    needs: list-forks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    strategy:
      matrix:
        repo: ${{ fromJson(needs.list-forks.outputs.repos) }}
    steps:
      - name: Dispatch to each fork
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: upstream-sync
          client-payload: '{"upstream":"cncf/foundation"}'
          repository: ${{ matrix.repo }}
